openfootball-repo:
  url: https://github.com/openfootball/es-espana.git
  user: ghuser
  pw: ghpw
  folder: ${java.io.tmpdir}/openfootball/es-espana
calendars:
  - name: Primera División
    url: https://www.marca.com/futbol/primera-division/calendario.html
    dest: 1-liga.txt
    locale: es-ES
  - name: Segunda División
    url: https://www.marca.com/futbol/segunda-division/calendario.html
    dest: 2-liga2.txt
    locale: es-ES
logging:
  level:
    root: INFO
    es.maxtuni.ofu: INFO
